# Build a model to classify region functions

This notebook shows how to use the ChromBERT-tools Python API `region_function_classification` to build a model for classifying region functions.

For the Python API, see [`examples/api/region_function_classification.ipynb`](../api/region_function_classification.ipynb).

If you need to use Apptainer container, please refer to the [`apptainer_use.ipynb`](apptainer_use.ipynb) tutorial for detailed instructions on using `apptainer exec` with `chrombert-tools`.

For more details, please refer to the [`region_function_classification`](https://chrombert-tools.readthedocs.io/en/latest/commands/region_function_classification.html) command documentation

### 1. build a model to classify the function different regions

In [1]:
%%bash
### build a model to classify the function different regions
    # group1: ezh2 and h3k27me3 co-binding region
    # group2: ezh2 binding region without h3k27me3

# takes approximately 20-40 minutes to run
# --function-bed: bed files of focus regions, Repeat this option to provide multiple classes.
# --function-name: Name of each functional region class.
# --dual-regulator: dual-functional regulator
# --ignore-regulator: Regulators to mask during fine-tuning

# Set the GPU device with CUDA_VISIBLE_DEVICES
export CUDA_VISIBLE_DEVICES=2
chrombert-tools region_function_classification \
    --function-bed "../data/hESC_GSM1003524_EZH2.bed;../data/hESC_GSM1498900_H3K27me3.bed" \
    --function-bed "../data/hESC_GSM1003524_EZH2.bed" \
    --function-name "ezh2_h3k27me3" \
    --function-name "ezh2" \
    --odir "./output_region_function_classification" \
    --ignore-regulator "H3K27me3;H3K27me3/H3K4me3" \
    --genome "hg38" \
    --resolution "1kb"

Note: All regulator names were converted to lowercase for matching.
Regulator count summary - requested: 2, matched in ChromBERT: 2, not found: 0, not found regulator: []
ChromBERT regulators: /mnt/Storage/home/chenqianqian/.cache/chrombert/data/config/hg38_6k_regulators_list.txt
Stage 1: Preparing dataset
[ezh2_h3k27me3 | hESC_GSM1003524_EZH2.bed] Region summary - total: 11896, overlapping with ChromBERT: 12101 (one region may overlap multiple ChromBERT regions, we keep overlaps with ≥50% coverage of either the ChromBERT bin or the input region), non-overlapping: 325
[ezh2_h3k27me3 | hESC_GSM1498900_H3K27me3.bed] Region summary - total: 8875, overlapping with ChromBERT: 14135 (one region may overlap multiple ChromBERT regions, we keep overlaps with ≥50% coverage of either the ChromBERT bin or the input region), non-overlapping: 2878
  ezh2_h3k27me3 (class 0): 5736 regions
[ezh2] Region summary - total: 11896, overlapping with ChromBERT: 12101 (one region may overlap multiple ChromBERT regions, we keep overlaps with ≥50% coverage of either the ChromBERT bin or the input region), non-overlapping: 325
  ezh2 (class 1): 11008 regions
  ezh2: removed 5736 overlapping regions
  ezh2_h3k27me3: 5736 (final)
  ezh2: 5272 (final)
  Total: 11008
  Fast mode: up to 10000 regions per class (total budget ≈ 20000)

/mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/chrombert_tools/cli/utils_classfication.py:176: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  combined.groupby("label", group_keys=False)

Finished stage 1
Stage 2: Fine-tuning (binary classification)

[Attempt 0/2] seed=55
Load pretrained ckpt /mnt/Storage/home/chenqianqian/.cache/chrombert/data/checkpoint/hg38_6k_1kb_pretrain.ckpt successfully!

Using bfloat16 Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs
You are using a CUDA device ('NVIDIA A100-PCIE-40GB') that has Tensor Cores. To properly utilize them, you should set `torch.set_float32_matmul_precision('medium' | 'high')` which will trade-off precision for performance. For more details, read https://pytorch.org/docs/stable/generated/torch.set_float32_matmul_precision.html#torch.set_float32_matmul_precision
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [2]
Loading `train_dataloader` to estimate number of stepping batches.
/mnt/Storage/home/chenqianqian/miniconda3/envs/chrombert/lib/python3.9/site-packages/lightning/pytorch/utilities/model_summary/model_summary.py:231: Precision bf16-mixed is not supported by the model summary.  Estimated model size in MB will not be accurate. Using 32 bits instead.

  | Name  | Type             | Params | Mode
---------------------------------------------------
0 | model | ChromBERTGeneral | 62.8 M | train
---------------------------------------------------
18.9 M    Trainable params
43.9 M    Non-trainable params
62.8 M    Total params
251.079   Total estimated model params size (MB)
153       Modules in train mode
0         Modules in eval mode
/mnt/Storage/home/chenqianqian/miniconda3/envs/chrombert/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/data_connector.py:484: Your `val_dataloader`'s sampler has shuffling enabled, it is strongly recommended that you turn shuffling off for val/test dataloaders.

Epoch 0:  20%|█▉        | 440/2202 [01:14<04:57,  5.92it/s, v_num=0]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]

Metric default_validation/auprc improved. New best score: 0.763

Validation DataLoader 0: 100%|██████████| 138/138 [00:12<00:00, 10.63it/s]
Epoch 0:  40%|███▉      | 880/2202 [02:41<04:02,  5.45it/s, v_num=0, default_validation/bce=0.630, default_validation/focal=0.156, default_validation/precision=0.755, default_validation/recall=0.511, default_validation/mcc=0.362, default_validation/f1=0.609, default_validation/auroc=0.740, default_validation/auprc=0.763, default_validation/acc=0.670, default_validation/mean_logit=-0.153, default_validation/median_logit=-0.199, default_validation/mean_prob=0.463, default_validation/median_prob=0.451]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]

Metric default_validation/auprc improved by 0.057 >= min_delta = 0.01. New best score: 0.821

Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.48it/s]
Epoch 0:  60%|█████▉    | 1320/2202 [04:09<02:46,  5.30it/s, v_num=0, default_validation/bce=0.536, default_validation/focal=0.173, default_validation/precision=0.802, default_validation/recall=0.615, default_validation/mcc=0.485, default_validation/f1=0.696, default_validation/auroc=0.800, default_validation/auprc=0.821, default_validation/acc=0.737, default_validation/mean_logit=-0.00287, default_validation/median_logit=-0.504, default_validation/mean_prob=0.482, default_validation/median_prob=0.377]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]

Metric default_validation/auprc improved by 0.021 >= min_delta = 0.01. New best score: 0.842

Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.56it/s]
Epoch 0:  80%|███████▉  | 1760/2202 [05:36<01:24,  5.22it/s, v_num=0, default_validation/bce=0.508, default_validation/focal=0.168, default_validation/precision=0.822, default_validation/recall=0.685, default_validation/mcc=0.553, default_validation/f1=0.747, default_validation/auroc=0.818, default_validation/auprc=0.842, default_validation/acc=0.774, default_validation/mean_logit=0.289, default_validation/median_logit=-0.285, default_validation/mean_prob=0.516, default_validation/median_prob=0.430]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]

Metric default_validation/auprc improved by 0.022 >= min_delta = 0.01. New best score: 0.864

Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.45it/s]
Epoch 0: 100%|█████████▉| 2200/2202 [07:05<00:00,  5.18it/s, v_num=0, default_validation/bce=0.488, default_validation/focal=0.174, default_validation/precision=0.794, default_validation/recall=0.723, default_validation/mcc=0.528, default_validation/f1=0.757, default_validation/auroc=0.834, default_validation/auprc=0.864, default_validation/acc=0.763, default_validation/mean_logit=0.301, default_validation/median_logit=-0.187, default_validation/mean_prob=0.523, default_validation/median_prob=0.453]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.43it/s]
Epoch 1:  20%|█▉        | 440/2202 [01:13<04:54,  5.98it/s, v_num=0, default_validation/bce=0.458, default_validation/focal=0.172, default_validation/precision=0.851, default_validation/recall=0.632, default_validation/mcc=0.557, default_validation/f1=0.725, default_validation/auroc=0.850, default_validation/auprc=0.869, default_validation/acc=0.774, default_validation/mean_logit=-0.084, default_validation/median_logit=-0.801, default_validation/mean_prob=0.441, default_validation/median_prob=0.311]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]

Metric default_validation/auprc improved by 0.032 >= min_delta = 0.01. New best score: 0.896

Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.56it/s]
Epoch 1:  40%|███▉      | 880/2202 [02:41<04:02,  5.46it/s, v_num=0, default_validation/bce=0.415, default_validation/focal=0.159, default_validation/precision=0.871, default_validation/recall=0.673, default_validation/mcc=0.606, default_validation/f1=0.759, default_validation/auroc=0.886, default_validation/auprc=0.896, default_validation/acc=0.799, default_validation/mean_logit=-0.0781, default_validation/median_logit=-0.848, default_validation/mean_prob=0.438, default_validation/median_prob=0.301]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.44it/s]
Epoch 1:  60%|█████▉    | 1320/2202 [04:08<02:45,  5.32it/s, v_num=0, default_validation/bce=0.455, default_validation/focal=0.214, default_validation/precision=0.913, default_validation/recall=0.613, default_validation/mcc=0.589, default_validation/f1=0.734, default_validation/auroc=0.876, default_validation/auprc=0.896, default_validation/acc=0.779, default_validation/mean_logit=-0.256, default_validation/median_logit=-1.09, default_validation/mean_prob=0.406, default_validation/median_prob=0.252]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.48it/s]
Epoch 1:  80%|███████▉  | 1760/2202 [05:36<01:24,  5.24it/s, v_num=0, default_validation/bce=0.454, default_validation/focal=0.233, default_validation/precision=0.942, default_validation/recall=0.606, default_validation/mcc=0.615, default_validation/f1=0.738, default_validation/auroc=0.883, default_validation/auprc=0.903, default_validation/acc=0.790, default_validation/mean_logit=-0.482, default_validation/median_logit=-1.34, default_validation/mean_prob=0.383, default_validation/median_prob=0.208]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]

Metric default_validation/auprc improved by 0.012 >= min_delta = 0.01. New best score: 0.908

Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.51it/s]
Epoch 1: 100%|█████████▉| 2200/2202 [07:04<00:00,  5.19it/s, v_num=0, default_validation/bce=0.436, default_validation/focal=0.197, default_validation/precision=0.925, default_validation/recall=0.630, default_validation/mcc=0.613, default_validation/f1=0.749, default_validation/auroc=0.890, default_validation/auprc=0.908, default_validation/acc=0.792, default_validation/mean_logit=-0.381, default_validation/median_logit=-1.05, default_validation/mean_prob=0.402, default_validation/median_prob=0.260]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.52it/s]
Epoch 2:  20%|█▉        | 440/2202 [01:13<04:55,  5.97it/s, v_num=0, default_validation/bce=0.480, default_validation/focal=0.272, default_validation/precision=0.929, default_validation/recall=0.624, default_validation/mcc=0.612, default_validation/f1=0.747, default_validation/auroc=0.885, default_validation/auprc=0.902, default_validation/acc=0.790, default_validation/mean_logit=-0.605, default_validation/median_logit=-1.51, default_validation/mean_prob=0.375, default_validation/median_prob=0.182]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.49it/s]
Epoch 2:  40%|███▉      | 880/2202 [02:40<04:01,  5.48it/s, v_num=0, default_validation/bce=0.500, default_validation/focal=0.272, default_validation/precision=0.933, default_validation/recall=0.607, default_validation/mcc=0.602, default_validation/f1=0.736, default_validation/auroc=0.876, default_validation/auprc=0.892, default_validation/acc=0.783, default_validation/mean_logit=-0.617, default_validation/median_logit=-1.42, default_validation/mean_prob=0.369, default_validation/median_prob=0.194]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.47it/s]
Epoch 2:  60%|█████▉    | 1320/2202 [04:07<02:45,  5.33it/s, v_num=0, default_validation/bce=0.412, default_validation/focal=0.190, default_validation/precision=0.860, default_validation/recall=0.708, default_validation/mcc=0.620, default_validation/f1=0.776, default_validation/auroc=0.886, default_validation/auprc=0.895, default_validation/acc=0.808, default_validation/mean_logit=0.0378, default_validation/median_logit=-0.793, default_validation/mean_prob=0.439, default_validation/median_prob=0.312]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]

Metric default_validation/auprc improved by 0.011 >= min_delta = 0.01. New best score: 0.919

Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.45it/s]
Epoch 2:  80%|███████▉  | 1760/2202 [05:35<01:24,  5.24it/s, v_num=0, default_validation/bce=0.386, default_validation/focal=0.161, default_validation/precision=0.882, default_validation/recall=0.749, default_validation/mcc=0.653, default_validation/f1=0.810, default_validation/auroc=0.903, default_validation/auprc=0.919, default_validation/acc=0.822, default_validation/mean_logit=0.180, default_validation/median_logit=-0.539, default_validation/mean_prob=0.471, default_validation/median_prob=0.369]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.52it/s]
Epoch 2: 100%|█████████▉| 2200/2202 [07:02<00:00,  5.21it/s, v_num=0, default_validation/bce=0.430, default_validation/focal=0.220, default_validation/precision=0.939, default_validation/recall=0.670, default_validation/mcc=0.654, default_validation/f1=0.782, default_validation/auroc=0.898, default_validation/auprc=0.916, default_validation/acc=0.813, default_validation/mean_logit=-0.354, default_validation/median_logit=-1.27, default_validation/mean_prob=0.402, default_validation/median_prob=0.219]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.46it/s]
Epoch 3:  20%|█▉        | 440/2202 [01:13<04:54,  5.99it/s, v_num=0, default_validation/bce=0.464, default_validation/focal=0.250, default_validation/precision=0.922, default_validation/recall=0.668, default_validation/mcc=0.629, default_validation/f1=0.775, default_validation/auroc=0.887, default_validation/auprc=0.909, default_validation/acc=0.801, default_validation/mean_logit=-0.402, default_validation/median_logit=-1.16, default_validation/mean_prob=0.404, default_validation/median_prob=0.238]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.53it/s]
Epoch 3:  40%|███▉      | 880/2202 [02:41<04:02,  5.46it/s, v_num=0, default_validation/bce=0.379, default_validation/focal=0.172, default_validation/precision=0.854, default_validation/recall=0.770, default_validation/mcc=0.644, default_validation/f1=0.810, default_validation/auroc=0.909, default_validation/auprc=0.919, default_validation/acc=0.821, default_validation/mean_logit=0.268, default_validation/median_logit=-0.475, default_validation/mean_prob=0.480, default_validation/median_prob=0.383]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]
Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.54it/s]
Epoch 3:  60%|█████▉    | 1320/2202 [04:08<02:46,  5.30it/s, v_num=0, default_validation/bce=0.462, default_validation/focal=0.277, default_validation/precision=0.934, default_validation/recall=0.680, default_validation/mcc=0.643, default_validation/f1=0.787, default_validation/auroc=0.898, default_validation/auprc=0.922, default_validation/acc=0.806, default_validation/mean_logit=-0.316, default_validation/median_logit=-1.31, default_validation/mean_prob=0.410, default_validation/median_prob=0.212]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation: |          | 0/? [00:00<?, ?it/s]
Validation DataLoader 0:   0%|          | 0/138 [00:00<?, ?it/s]

Monitored metric default_validation/auprc did not improve in the last 5 records. Best score: 0.919. Signaling Trainer to stop.

Validation DataLoader 0: 100%|██████████| 138/138 [00:13<00:00, 10.49it/s]
Epoch 3:  60%|█████▉    | 1320/2202 [04:24<02:56,  5.00it/s, v_num=0, default_validation/bce=0.431, default_validation/focal=0.226, default_validation/precision=0.930, default_validation/recall=0.680, default_validation/mcc=0.637, default_validation/f1=0.786, default_validation/auroc=0.900, default_validation/auprc=0.926, default_validation/acc=0.803, default_validation/mean_logit=-0.136, default_validation/median_logit=-0.93, default_validation/mean_prob=0.432, default_validation/median_prob=0.283]
Evaluating the finetuned model performance
Load pretrained ckpt /mnt/Storage/home/chenqianqian/.cache/chrombert/data/checkpoint/hg38_6k_1kb_pretrain.ckpt successfully!
Loading checkpoint from /mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/examples/cli/output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt
Loading from pl module, remove prefix 'model.'
Loading from pl module, replace 'pretrain_model' with 'pretrain_model.chrombert'
Loaded 111/111 parameters
ft_ckpt: /mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/examples/cli/output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt, test_metrics: {'auroc': 0.8981403112411499, 'auprc': 0.8998041152954102, 'mcc': 0.6202204823493958, 'f1': 0.7663755416870117, 'precision': 0.8819095492362976, 'recall': 0.6776061654090881}
Attempt metrics: auprc=0.8998041152954102
Accepted run (auprc=0.8998 >= 0.2).

Finished stage 2: obtained a fine-tuned ChromBERT
Best auprc=0.8998041152954102, metrics={'auroc': 0.8981403112411499, 'auprc': 0.8998041152954102, 'mcc': 0.6202204823493958, 'f1': 0.7663755416870117, 'precision': 0.8819095492362976, 'recall': 0.6776061654090881, 'ft_ckpt': '/mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/examples/cli/output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt'}
Finished stage 2
Stage 3: Predicting
Region summary - total: 1101, overlapping with ChromBERT: 1101 (one region may overlap multiple ChromBERT regions, we keep overlaps with ≥50% coverage of either the ChromBERT bin or the input region), non-overlapping: 0
  Predict input: ./output_region_function_classification/predict/model_input.tsv

Predicting: 100%|██████████| 276/276 [00:53<00:00,  5.15it/s]

  Predictions saved: /mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/examples/cli/output_region_function_classification/predict/predictions.csv  (1101 regions)
Finished stage 3

============================================================
All stages completed!
============================================================
Fine-tuned model saved in: ./output_region_function_classification/train/try_00_seed_55
Classes (2): ezh2_h3k27me3, ezh2
Predictions: ./output_region_function_classification/predict/predictions.csv
Fine-tuned checkpoint: /mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/examples/cli/output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt
Predictions: ./output_region_function_classification/predict/predictions.csv

### 2.Interpretation

After building a model, we can use the interpretation layer of ChromBERT-tools to derive biological insights.

We display the important factors between different region groups using the fine-tuned checkpoint.

In [2]:
import glob
ft_ckpt_dir = "./output_region_function_classification/train/**/*.ckpt"  # Use checkpoints generated by the command above

ft_ckpt = glob.glob(ft_ckpt_dir, recursive=True)[0]
ft_ckpt

'./output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt'

In [3]:
import pandas as pd
test_data = pd.read_csv("./output_region_function_classification/dataset/test_sampled.csv") # test data generated by the command above
odir="interpretation_important_factor_effect_ezh2"
!mkdir -p "interpretation_important_factor_effect_ezh2"
ezh2_k27me3_region_sample_file = f"{odir}/ezh2_h3k27me3_region_sample.csv"
ezh2_only_region_sample_file = f"{odir}/ezh2_only_region_sample.csv"
test_data.query("label==0").to_csv(ezh2_k27me3_region_sample_file,index=False) # Class 0 regions in the test data
test_data.query("label==1").to_csv(ezh2_only_region_sample_file,index=False) # Class 1 regions in the test data

In [10]:

# The ``interpret_regulator_effects_between_region_groups`` command generates regulator embeddings for different region groups and calculates the embedding difference of each regulator between groups as 1 − cosine similarity. Regulators with larger embedding differences are considered more likely to be key regulators.

# --region1-file: the region group 1
# --region2-file: the region group 2
# --odir: output directory
# --genome: genome
# --resolution: resolution
# --ft-ckpt: fine-tuned model checkpoint

# Set the GPU device with CUDA_VISIBLE_DEVICES
!export CUDA_VISIBLE_DEVICES=2
!chrombert-tools interpret_regulator_effects_between_region_groups \
    --region1-file "./interpretation_important_factor_effect_ezh2/ezh2_h3k27me3_region_sample.csv" \
    --region2-file "./interpretation_important_factor_effect_ezh2/ezh2_only_region_sample.csv" \
    --odir "./output_region_function_classification" \
    --genome "hg38" \
    --resolution "1kb" \
    --ft-ckpt {ft_ckpt} \
    --model-config "./output_region_function_classification/model_config.json" \
    --data-config './output_region_function_classification/dataset_config.json'

Region summary - total: 583, overlapping with ChromBERT: 583 (one region may overlap multiple ChromBERT regions, we keep overlaps with ≥50% coverage of either the ChromBERT bin or the input region), non-overlapping: 0
Region summary - total: 518, overlapping with ChromBERT: 518 (one region may overlap multiple ChromBERT regions, we keep overlaps with ≥50% coverage of either the ChromBERT bin or the input region), non-overlapping: 0
Load pretrained ckpt /mnt/Storage/home/chenqianqian/.cache/chrombert/data/checkpoint/hg38_6k_1kb_pretrain.ckpt successfully!
Loading checkpoint from /mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/examples/cli/output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt
Loading from pl module, remove prefix 'model.'
Loading from pl module, replace 'pretrain_model' with 'pretrain_model.chrombert'
Loaded 111/111 parameters
100%|█████████████████████████████████████████| 146/146 [00:23<00:00,  6.19it/s]
100%|█████████████████████████████████████████| 130/130 [00:20<00:00,  6.40it/s]
Identify key regulators across regions(top 25)
      factors  similarity  rank  embedding_shift
0       suz12    0.833698     1         0.166302
1       dnase    0.846664     2         0.153336
2        ezh2    0.875976     3         0.124024
3       ssu72    0.885919     4         0.114081
4         sp4    0.891500     5         0.108500
5        taf7    0.893866     6         0.106134
6         tbp    0.894265     7         0.105735
7       fgfr1    0.894296     8         0.105704
8        cbx3    0.895087     9         0.104913
9        ctcf    0.896610    10         0.103390
10     supt5h    0.897251    11         0.102749
11       chd8    0.897304    12         0.102696
12      ep300    0.899515    13         0.100485
13      sin3a    0.899922    14         0.100078
14       taf1    0.900326    15         0.099674
15      creb1    0.900824    16         0.099176
16    h3k4me3    0.901658    17         0.098342
17       ezh1    0.902089    18         0.097911
18    h3k27ac    0.902899    19         0.097101
19     polr2a    0.903105    20         0.096895
20   atac-seq    0.903982    21         0.096018
21     h3k9ac    0.904405    22         0.095595
22        max    0.904692    23         0.095308
23       brd4    0.905221    24         0.094779
24  h2ak119ub    0.905373    25         0.094627
Finished
Used fine-tuned ChromBERT checkpoint: ./output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt
Key regulators across regions saved to: ./output_region_function_classification/results/factor_importance_rank.csv

In [11]:
import pandas as pd
factor_importance_rank = pd.read_csv("output_region_function_classification/results/factor_importance_rank.csv")
factor_importance_rank.head(n=25)

      factors  similarity  rank  embedding_shift
0       suz12    0.833698     1         0.166302
1       dnase    0.846664     2         0.153336
2        ezh2    0.875976     3         0.124024
3       ssu72    0.885919     4         0.114081
4         sp4    0.891500     5         0.108500
5        taf7    0.893866     6         0.106134
6         tbp    0.894265     7         0.105735
7       fgfr1    0.894296     8         0.105704
8        cbx3    0.895087     9         0.104913
9        ctcf    0.896610    10         0.103390
10     supt5h    0.897251    11         0.102749
11       chd8    0.897304    12         0.102696
12      ep300    0.899515    13         0.100485
13      sin3a    0.899922    14         0.100078
14       taf1    0.900326    15         0.099674
15      creb1    0.900824    16         0.099176
16    h3k4me3    0.901658    17         0.098342
17       ezh1    0.902089    18         0.097911
18    h3k27ac    0.902899    19         0.097101
19     polr2a    0.903105    20         0.096895
20   atac-seq    0.903982    21         0.096018
21     h3k9ac    0.904405    22         0.095595
22        max    0.904692    23         0.095308
23       brd4    0.905221    24         0.094779
24  h2ak119ub    0.905373    25         0.094627

### 2.Interpretation (cofactor)

After building a model, we can use the interpretation layer of ChromBERT-tools to derive biological insights.

Here, we identify important EZH2 cofactors across different region groups using the fine-tuned checkpoint.

In [12]:

# identify the important cofactors of EZH2 for ezh2_h3k27me3 region (class 0)

# The `interpret_regulator_regulator_interactions` subcommand generates context-aware regulator embeddings and calculates the cosine similarity of each regulator pair. Regulators with higher cosine similarity are considered more likely to interact.

# --region: the region group 1
# --regulator: focus regulator
# --odir: output directory
# --genome: Reference genome
# --resolution: Resolution
# --ft-ckpt: Fine-tuned checkpoint
# --quantile: Cosine-similarity quantile threshold for defining edges
# --model-config: Model config generated by the command above
# --data-config: Data config generated by the command above

# Set the GPU device with CUDA_VISIBLE_DEVICES
!export CUDA_VISIBLE_DEVICES=2

!chrombert-tools interpret_regulator_regulator_interactions \
    --region "./interpretation_important_factor_effect_ezh2/ezh2_h3k27me3_region_sample.csv" \
    --regulator "ezh2" \
    --odir "./output_regulator_network_ezh2_1" \
    --ft-ckpt {ft_ckpt} \
    --genome "hg38" \
    --resolution "1kb" \
    --quantile 0.95 \
    --model-config "./output_region_function_classification/model_config.json" \
    --data-config './output_region_function_classification/dataset_config.json'

Region summary - total: 583, overlapping with ChromBERT: 583 (one region may overlap multiple ChromBERT regions, we keep overlaps with ≥50% coverage of either the ChromBERT bin or the input region), non-overlapping: 0
Note: All regulator names were converted to lowercase for matching.
Regulator count summary - requested: 1, matched in ChromBERT: 1, not found: 0, not found regulator: []
ChromBERT regulators: /mnt/Storage/home/chenqianqian/.cache/chrombert/data/config/hg38_6k_regulators_list.txt
Load pretrained ckpt /mnt/Storage/home/chenqianqian/.cache/chrombert/data/checkpoint/hg38_6k_1kb_pretrain.ckpt successfully!
Loading checkpoint from /mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/examples/cli/output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt
Loading from pl module, remove prefix 'model.'
Loading from pl module, replace 'pretrain_model' with 'pretrain_model.chrombert'
Loaded 111/111 parameters
100%|█████████████████████████████████████████| 146/146 [00:23<00:00,  6.21it/s]
Total graph nodes: 1014
Total graph edges (threshold=0.623): 28650
Regulator subnetwork saved to: ./output_regulator_network_ezh2_1/subnetwork_ezh2_k1_q0.950_thr0.623.pdf
Finished!
Saved outputs to: ./output_regulator_network_ezh2_1
Regulator cosine similarity saved to: ./output_regulator_network_ezh2_1/regulator_cosine_similarity.tsv
Total graph edges saved to: ./output_regulator_network_ezh2_1/total_graph_edge_threshold0.623_quantile0.950.tsv

In [13]:

# identify the important cofactors of EZH2 for ezh2 binding region (class 1)

# The `interpret_regulator_regulator_interactions` subcommand generates context-aware regulator embeddings and calculates the cosine similarity of each regulator pair. Regulators with higher cosine similarity are considered more likely to interact.

# --region: the region group 1
# --regulator: focus regulator
# --odir: output directory
# --genome: Reference genome
# --resolution: Resolution
# --ft-ckpt: Fine-tuned checkpoint
# --quantile: Cosine-similarity quantile threshold for defining edges
# --model-config: Model config generated by the command above
# --data-config: Data config generated by the command above

# Set the GPU device with CUDA_VISIBLE_DEVICES
!export CUDA_VISIBLE_DEVICES=2

!chrombert-tools interpret_regulator_regulator_interactions \
    --region "./interpretation_important_factor_effect_ezh2/ezh2_only_region_sample.csv" \
    --regulator "ezh2" \
    --odir "./output_regulator_network_ezh2_2" \
    --ft-ckpt {ft_ckpt} \
    --genome "hg38" \
    --resolution "1kb" \
    --quantile 0.95 \
    --model-config "./output_region_function_classification/model_config.json" \
    --data-config './output_region_function_classification/dataset_config.json'

Region summary - total: 518, overlapping with ChromBERT: 518 (one region may overlap multiple ChromBERT regions, we keep overlaps with ≥50% coverage of either the ChromBERT bin or the input region), non-overlapping: 0
Note: All regulator names were converted to lowercase for matching.
Regulator count summary - requested: 1, matched in ChromBERT: 1, not found: 0, not found regulator: []
ChromBERT regulators: /mnt/Storage/home/chenqianqian/.cache/chrombert/data/config/hg38_6k_regulators_list.txt
Load pretrained ckpt /mnt/Storage/home/chenqianqian/.cache/chrombert/data/checkpoint/hg38_6k_1kb_pretrain.ckpt successfully!
Loading checkpoint from /mnt/Storage2/home/chenqianqian/projects/chrombert/chrombert_tools/ChromBERT-tools/examples/cli/output_region_function_classification/train/try_00_seed_55/lightning_logs/lightning_logs/version_0/checkpoints/epoch=3-step=125.ckpt
Loading from pl module, remove prefix 'model.'
Loading from pl module, replace 'pretrain_model' with 'pretrain_model.chrombert'
Loaded 111/111 parameters
100%|█████████████████████████████████████████| 130/130 [00:20<00:00,  6.27it/s]
Total graph nodes: 1033
Total graph edges (threshold=0.568): 28650
Regulator subnetwork saved to: ./output_regulator_network_ezh2_2/subnetwork_ezh2_k1_q0.950_thr0.568.pdf
Finished!
Saved outputs to: ./output_regulator_network_ezh2_2
Regulator cosine similarity saved to: ./output_regulator_network_ezh2_2/regulator_cosine_similarity.tsv
Total graph edges saved to: ./output_regulator_network_ezh2_2/total_graph_edge_threshold0.568_quantile0.950.tsv

In [16]:
# total graph edges on different regions
edges_file2 = glob.glob("output_regulator_network_ezh2_2/total_graph_edge*.tsv", recursive=True)[0]
df_edges_2 = pd.read_csv(edges_file2,sep="\t")

edges_file1 = glob.glob("output_regulator_network_ezh2_1/total_graph_edge*.tsv", recursive=True)[0]
df_edges_1 = pd.read_csv(edges_file1,sep="\t")

# ezh2 subnetwork on different regions
df_edges_2_ezh2 = df_edges_2.query("node1=='ezh2'")
df_edges_1_ezh2 = df_edges_1.query("node1=='ezh2'")

In [17]:
# merge the ezh2 subnetwork on different regions
merge_df = pd.merge(df_edges_1_ezh2, df_edges_2_ezh2, on="node2", how="outer",suffixes=("_ezh2_1", "_ezh2_2"))

In [18]:
merge_df.query("node1_ezh2_1 != node1_ezh2_1") # specific cofactor on function region2

,node1_ezh2_1,node2,cosine_similarity_ezh2_1,node1_ezh2_2,cosine_similarity_ezh2_2
0,NaN,foxm1,NaN,ezh2,0.623480
1,NaN,h2a,NaN,ezh2,0.569144
3,NaN,h3,NaN,ezh2,0.585986
4,NaN,hdac1,NaN,ezh2,0.585492
5,NaN,hinfp,NaN,ezh2,0.595692
7,NaN,junb,NaN,ezh2,0.574974
8,NaN,kdm1a,NaN,ezh2,0.570171
10,NaN,kmt2d,NaN,ezh2,0.568759
11,NaN,med1,NaN,ezh2,0.586996
14,NaN,polr3d,NaN,ezh2,0.580469
15,NaN,rela,NaN,ezh2,0.593163
16,NaN,rest,NaN,ezh2,0.589104
19,NaN,smad4,NaN,ezh2,0.579999
20,NaN,smarca4,NaN,ezh2,0.572757
21,NaN,stat1,NaN,ezh2,0.613834
22,NaN,stat3,NaN,ezh2,0.644840
24,NaN,tcf7l2,NaN,ezh2,0.580286
25,NaN,tfdp1,NaN,ezh2,0.575265
26,NaN,tp53,NaN,ezh2,0.589069
27,NaN,ubtf,NaN,ezh2,0.643334
28,NaN,zbtb33,NaN,ezh2,0.592518
29,NaN,znf274,NaN,ezh2,0.585578

In [19]:
merge_df.query("node1_ezh2_2 != node1_ezh2_2") # specific cofactor on function region1

,node1_ezh2_1,node2,cosine_similarity_ezh2_1,node1_ezh2_2,cosine_similarity_ezh2_2
6,ezh2,jarid2,0.641228,NaN,NaN
9,ezh2,kdm2b,0.632823,NaN,NaN
12,ezh2,pcgf1,0.646379,NaN,NaN

In [20]:
merge_df.query("node1_ezh2_2 == node1_ezh2_2 and node1_ezh2_1 == node1_ezh2_1 and (cosine_similarity_ezh2_1 - cosine_similarity_ezh2_2 > 0.1 or cosine_similarity_ezh2_1 - cosine_similarity_ezh2_2 < -0.1)") # specific cofactor on function region1 and region2

,node1_ezh2_1,node2,cosine_similarity_ezh2_1,node1_ezh2_2,cosine_similarity_ezh2_2
2,ezh2,h2ak119ub,0.725592,ezh2,0.616852